config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:index]
  resources :duong, only: [:index]
  resources :tuition, only:[:index]


  resources :student do
        collection do
          get 'back_to_index'
        end
        member do
          get 'back_to_show'
        end
    end


  # get 'student/new', to: 'student#new'
  # root 'student#index'



  resources :teacher do
    collection do
      get 'back_to_index'
    end
    member do
      get 'back_to_show'
    end
  end
  resources :transcript, only:[:index]
  resources :classs, only:[:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classs.rb
class Classs < ApplicationRecord

  end

app/models/duong.rb
class Duong < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

end

app/models/student.rb
class Student < ApplicationRecord

end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/transcript.rb
class Transcript < ApplicationRecord

end

app/models/tuition.rb
class Tuition < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/classs_controller.rb
class ClasssController < ActionController::Base
  def index
    @classs = Classs.all
  end
end

app/controllers/duong_controller.rb
class DuongController < ActionController::Base
  def index
    @duong = Duong.all
  end
end

app/controllers/student_controller.rb
class StudentController < ActionController::Base
  def index
    @student = Student.all
    @student_page = Student.page(params[:page]).per(10)
    if params[:query].present?
      @student = Student.where("student_code LIKE ?", "%#{params[:query]}%")

    end

    # if params[:query].present?
    #   @ids = Student.where("student_code LIKE ?", "%#{params[:query]}%").ids
    # end
  end


  def back_to_show
    @student = Student.find(params[:id])
    redirect_to student_path(@student)
  end
  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def back_to_index
    redirect_to student_index_path
  end


  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_index_path, notice: 'Student was successfully created'
    else
      render :new
    end
  end

  def edit
    @student =Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student, notice: 'Thong tin sinh vien da duoc cap nhat'
    else
      render :edit
    end
  end


  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to student_index_url, notice: 'Student was successfully destroyed'
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:student_code, :student_name, :date_of_birth, :address, :gmail, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classs_helper.rb
module ClasssHelper
end

app/helpers/create_classed_helper.rb
module CreateClassedHelper
end

app/helpers/duong_helper.rb
module DuongHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/transcript_helper.rb
module TranscriptHelper
end

app/helpers/tuition_helper.rb
module TuitionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/student/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<h1> Chỉnh sửa thông tin sinh viên </h1>
<h2>Thông tin sinh viên </h2>

<p class="form-label"><strong>Mã Sinh viên:</strong> <%= @student.student_code %></p>
<p class="form-label"><strong>Tên Sinh Viên:</strong> <%= @student.student_name %></p>
<p class="form-label"><strong>Ngày Sinh:</strong> <%= @student.date_of_birth %></p>
<p class="form-label"><strong>Địa chỉ:</strong> <%= @student.address %></p>
<p class="form-label"><strong>Gmail:</strong> <%= @student.gmail %></p>
<p class="form-label"><strong>Số Điện Thoại:</strong> <%= @student.phone %></p>

<%= form_with(model: @student, local: true) do |form| %>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :student_code %></label>
    <%= form.text_field :student_code,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :student_name %></label>
    <%= form.text_field :student_name,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :date_of_birth %></label>
    <%= form.text_field :date_of_birth,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :address %></label>
    <%= form.text_field :address,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :gmail %></label>
    <%= form.text_field :gmail,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :phone %></label>
    <%= form.text_field :phone,  class:'form-control'%>
  </div>

  <%= form.submit 'Lưu Chỉnh Sửa' %>

  <%= link_to 'Quay Lại', back_to_show_student_path(@student) %>
<% end %>

app/views/student/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<div class="centered-content">
<h1>Thông tin sinh viên</h1>

<!-- tim kiem sinh vien -->
<h4>Tìm kiếm sinh viên</h4>
<%= form_tag(student_index_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: 'Nhập mã sinh viên' %>
  <%= submit_tag 'Tìm Kiếm' %>
<% end %>

<table class="student-table">
  <tr>
    <th>Student Code</th>
    <th>Student Name</th>
    <th>Date of birth</th>
    <th>Address</th>
    <th>Gmail</th>
    <th>Phone</th>
    <th>Action</th>
  </tr>

  <% @student.each do |student| %>

    <tr <%= @ids&.include?(student.id) ? 'active' : '' %>">
      <td class="center-text"><%=  student.student_code  %></td>
      <td class="center-text"><%=  student.student_name %></td>
      <td class="center-text"><%=  student.date_of_birth  %></td>
      <td class="center-text"><%=  student.address  %></td>
      <td class="center-text"><%=  student.gmail  %></td>
      <td class="center-text"><%=  student.phone  %></td>
      <td class="center-text"><%= link_to 'Edit', "/student/#{student.id}" %></td>
      <td class="center-text"><%= button_to 'Xóa', student_path(student.id), method: :delete %></td>
    </tr>
  <% end %>
</table>


<!-- tao bang sinh vien -->
<%= link_to 'Thêm Sinh Viên', new_student_path %>
<%= paginate @student_page %>
</div>
<style>
    table{
        background-color: aliceblue;
    }
    table,tr,th,td{
        padding: 16px;
        border: 1px solid black;
        border-collapse: collapse;
    }
    .centered-content {
        text-align: center;
    }
    .student-table {
        margin: 0 auto;
    }

</style>

app/views/student/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<h1>Thêm thông tin sinh viên</h1>
<%= form_with(model: @student, url: student_index_path,  method: :post, local: true) do |form| %>
  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :student_code %></label>
    <%= form.text_field :student_code,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :student_name %></label>
    <%= form.text_field :student_name,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :date_of_birth %></label>
    <%= form.text_field :date_of_birth,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :address %></label>
    <%= form.text_field :address,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :gmail %></label>
    <%= form.text_field :gmail,  class:'form-control'%>
  </div>

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label"><%= form.label :phone %></label>
    <%= form.text_field :phone,  class:'form-control'%>
  </div>

  <%= form.submit 'Lưu' %>
<% end %>
<%= link_to 'Quay lại', student_index_path %>

app/views/student/show.html.erb
<h1>Chỉnh sửa thông tin sinh viên</h1>
<h2>Thông tin sinh viên</h2>

<p><strong>Mã Sinh Viên:</strong> <%= @student.student_code %></p>
<p><strong>Tên Sinh Viên:</strong> <%= @student.student_name %></p>
<p><strong>Ngày Sinh:</strong> <%= @student.date_of_birth %></p>
<p><strong>Địa Chỉ:</strong> <%= @student.address %></p>
<p><strong>Gmail:</strong> <%= @student.gmail %></p>
<p><strong>Số Điện Thoại:</strong> <%= @student.phone %></p>



<%= link_to 'Quay Lại', back_to_index_student_index_path %> |
<%= link_to 'Chỉnh Sửa', edit_student_path(@student) %>