config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:index]
  resources :duong, only: [:index]
  resources :tuition, only:[:index]


  resources :student do
        collection do
          get 'back_to_index'
        end
        member do
          get 'back_to_show'
        end
    end


  # get 'student/new', to: 'student#new'
  # root 'student#index'



  resources :teacher do
    collection do
      get 'back_to_index'
    end
    member do
      get 'back_to_show'
    end
  end
  resources :transcript, only:[:index]
  resources :classs, only:[:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classs.rb
class Classs < ApplicationRecord

  end

app/models/duong.rb
class Duong < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

end

app/models/student.rb
class Student < ApplicationRecord

end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/transcript.rb
class Transcript < ApplicationRecord

end

app/models/tuition.rb
class Tuition < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/classs_controller.rb
class ClasssController < ActionController::Base
  def index
    @classs = Classs.all
  end
end

app/controllers/duong_controller.rb
class DuongController < ActionController::Base
  def index
    @duong = Duong.all
  end
end

app/controllers/teacher_controller.rb
class TeacherController < ActionController::Base
  def index
    @teacher = Teacher.all
    @teacher_page = Teacher.page(params[:page]).per(10)
    if params[:query].present?
      @ids = Teacher.where("teacher_code LIKE ?", "%#{params[:query]}%").ids
    end
  end


  def back_to_show
    @teacher = Teacher.find(params[:id])
    redirect_to teacher_path(@teacher)
  end
  def show
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def back_to_index
    redirect_to teacher_index_path
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to teacher_index_path, notice: 'Teacher was successfully created'
    else
      render :new
    end
  end

  def edit
    @teacher =Teacher.find(params[:id])
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher, notice: 'Teacher was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to teacher_index_url, notice: 'Teacher was successfully destroyed'
  end

  private

  def set_teacher
    @teacher =Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:teacher_code, :teacher_name, :date_of_birth, :gender, :gmail, :phone)
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classs_helper.rb
module ClasssHelper
end

app/helpers/duong_helper.rb
module DuongHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/transcript_helper.rb
module TranscriptHelper
end

app/helpers/tuition_helper.rb
module TuitionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teacher/edit.html.erb
<h1>Chỉnh sửa thông tin giao vien </h1>
<h2>Thông tin giao vien </h2>

<p><strong>Mã giao vien:</strong> <%= @teacher.teacher_code %></p>
<p><strong>Tên Giao Viên:</strong> <%= @teacher.teacher_name %></p>
<p><strong>Ngày Sinh:</strong> <%= @teacher.date_of_birth %></p>
<p><strong>Gioi Tinh:</strong> <%= @teacher.gender %></p>
<p><strong>Gmail:</strong> <%= @teacher.gmail %></p>
<p><strong>Số Điện Thoại:</strong> <%= @teacher.phone %></p>

<%= form_with(model: @teacher, local: true) do |form| %>
  <div class="field">
    <%= form.label :teacher_code %>
    <%= form.text_field :teacher_code %>
  </div>

  <div class="field">
    <%= form.label :teacher_name %>
    <%= form.text_field :teacher_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :gmail %>
    <%= form.text_field :gmail %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <%= form.submit 'Lưu Chỉnh Sửa' %>

  <%= link_to 'Quay Lại', back_to_show_teacher_path(@teacher) %>
<% end %>

app/views/teacher/index.html.erb
<h1>Thông tin giao vien</h1>

<!-- tim kiem giao vien -->
<%= form_tag(teacher_index_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: 'Nhập tên giao vien' %>
  <%= submit_tag 'Tìm Kiếm' %>
<% end %>

<table id="teacherTable">
  <tr>
    <th>Teacher Code</th>
    <th>Teacher Name</th>
    <th>Date of birth</th>
    <th>Gender</th>
    <th>Gmail</th>
    <th>Phone</th>
    <th>Action</th>
  </tr>

  <% @teacher.each do |teacher| %>
    <tr class="<%= @ids&.include?(teacher.id) ? 'active' : '' %>">
      <td><%=  teacher.teacher_code  %></td>
      <td><%=  teacher.teacher_name %></td>
      <td><%=  teacher.date_of_birth  %></td>
      <td><%=  teacher.gender  %></td>
      <td><%=  teacher.gmail  %></td>
      <td><%=  teacher.phone  %></td>
      <td><%= link_to 'Edit', "/teacher/#{teacher.id}" %></td>
      <td><%= button_to 'Xóa', teacher_path(teacher.id), method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= paginate @teacher_page %>
<!-- tao bang giao vien -->
<%= link_to 'Thêm Giao Viên', new_teacher_path %>

<style>
    table{
        background-color: aliceblue;
    }
    table,tr,th,td{
        padding: 20px;
        border: 1px solid black;
        border-collapse: collapse;
    }

</style>

app/views/teacher/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<h1>Thêm thông tin giao vien</h1>
<%= form_with(model: @teacher, url: teacher_index_path,  method: :post, local: true) do |form| %>
  <div class="field">
    <%= form.label :teacher_code %>
    <%= form.text_field :teacher_code %>
  </div>

  <div class="field">
    <%= form.label :teacher_name %>
    <%= form.text_field :teacher_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :gmail %>
    <%= form.text_field :gmail %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <%= form.submit 'Lưu' %>
<% end %>
<%= link_to 'Quay lại', teacher_index_path %>

app/views/teacher/show.html.erb
<h1>Information teachers</h1>
<p><strong>Teacher code</strong> <%= @teacher.teacher_code %></p>
<p><strong>Teacher name</strong> <%= @teacher.teacher_name %></p>
<p><strong>Date of birth</strong> <%= @teacher.date_of_birth %></p>
<p><strong>Gender</strong> <%= @teacher.gender %></p>
<p><strong>Gmail</strong> <%= @teacher.gmail %></p>
<p><strong>Phone</strong> <%= @teacher.phone %></p>
<%=link_to 'Edit', edit_teacher_path(@teacher) %> |

<%= link_to 'Quay Lại', back_to_index_teacher_index_path %> |
<%= link_to 'Chỉnh Sửa', edit_teacher_path(@teacher) %>